version: "3.9"
services:
     databases:
               build: 
                      context: .
                      dockerfile: server.dockerfile
               ports: 
                  - "330:5432"
               volumes:
                  - ./data:/var/lib/postresql/data
               